id: '16208362544700.4871843390485566'
definitionId: smartTable
parentSlotId: '17193264047810.42427968323646414'
styles:
  xl:
    gridItem:
      id: '16208362544700.4871843390485566'
      x: 0
      y: 0
      w: 18
      h: 125
    flex:
      size:
        widthValue: auto
        heightValue: 320
        heightUnit: px
      grow: 0
      shrink: 0
  xs:
    gridItem:
      id: '16208362544700.4871843390485566'
      x: 0
      y: 0
      w: 18
      h: 125
    flex:
      size:
        widthValue: auto
        heightValue: 320
        heightUnit: px
      grow: 0
      shrink: 0
properties:
  name: productsTable
  data: '{{actions.products.data}}'
  title: ''
  limit: '10'
  showLoading:
    value: false
    dataValue: '{{actions.products.loading}}'
    withData: false
  selectedRowIndex: '0'
  triggerRowSelectOnInit:
    value: true
    dataValue: 'false'
    withData: false
  __UIBAKERY__RESPONSIVE__SHOW__CONDITION__CODE__:
    - xl
    - xs
  selectRowOnEditButtonClick:
    value: false
    dataValue: 'false'
    withData: false
  rowHeight: dynamic
  showFooter:
    value: true
    dataValue: 'true'
    withData: false
  containerStyles:
    withData: false
    dataValue: |-
      {
        padding: 'default',
        shadow: 'default',
        border: 'default'
      }
    value:
      padding: default
      shadow: default
      border: default
actions: {}
index: 1
slots:
  - id: '16208362544700.44125583843162275'
    name: columns
    children:
      - id: '16208362762020.031929538095960774'
        definitionId: atomicString
        parentSlotId: '16208362544700.44125583843162275'
        styles:
          xl:
            visible: true
        properties:
          name: atomicString
          prop: productCode
          primaryKey: true
          filter: true
          width: '100'
          length:
            value: {}
            withData: false
            dataValue: '[0, 10]'
          textStyle:
            transform: none
            styles:
              - bold
          __UIBAKERY__RESPONSIVE__SHOW__CONDITION__CODE__:
            - xl
            - xs
        index: 0
        slots: []
      - id: '16208362762030.05798874213812355'
        definitionId: atomicString
        parentSlotId: '16208362544700.44125583843162275'
        styles:
          xl:
            visible: false
        properties:
          name: atomicString4
          prop: productScale
          primaryKey: false
          filter: true
          width: 150
          __UIBAKERY__RESPONSIVE__SHOW__CONDITION__CODE__:
            - xl
            - xs
        index: 3
        slots: []
      - id: '16208362762030.7948938689040528'
        definitionId: atomicString
        parentSlotId: '16208362544700.44125583843162275'
        styles:
          xl:
            visible: false
        properties:
          name: atomicString6
          prop: productDescription
          primaryKey: false
          filter: true
          width: 150
          __UIBAKERY__RESPONSIVE__SHOW__CONDITION__CODE__:
            - xl
            - xs
        index: 5
        slots: []
      - id: '16208362762030.8649600459827069'
        definitionId: atomicNumber
        parentSlotId: '16208362544700.44125583843162275'
        styles:
          xl:
            visible: true
        properties:
          name: atomicNumber
          prop: quantityInStock
          primaryKey: false
          filter: true
          width: 90
          __UIBAKERY__RESPONSIVE__SHOW__CONDITION__CODE__:
            - xl
            - xs
          filterVariation:
            value: range
            dataValue: range
            withData: false
        index: 6
        slots: []
      - id: '16208362762030.33725726176059045'
        definitionId: atomicNumber
        parentSlotId: '16208362544700.44125583843162275'
        styles:
          xl:
            visible: false
        properties:
          name: atomicNumber3
          prop: MSRP
          primaryKey: false
          filter: true
          width: 90
          __UIBAKERY__RESPONSIVE__SHOW__CONDITION__CODE__:
            - xl
            - xs
          filterVariation:
            value: range
            dataValue: range
            withData: false
        index: 8
        slots: []
      - id: '16208362762030.8319694628095786'
        definitionId: atomicString
        parentSlotId: '16208362544700.44125583843162275'
        styles:
          xl:
            visible: false
        properties:
          name: atomicString5
          prop: productVendor
          primaryKey: false
          filter: true
          width: 150
          length:
            value: {}
            withData: false
            dataValue: '[0, 10]'
          __UIBAKERY__RESPONSIVE__SHOW__CONDITION__CODE__:
            - xl
            - xs
        index: 4
        slots: []
      - id: '16208362762030.4185685913373376'
        definitionId: atomicMultiselect
        parentSlotId: '16208362544700.44125583843162275'
        styles: {}
        properties:
          name: atomicMultiselect
          prop: productLine
          primaryKey: false
          filter: true
          width: 150
          options:
            value:
              - title: Active
                value: active
                color: success
                __UIBAKERY__SYSTEM_ID__: '16255749563400.35800609955864715'
              - title: Not active
                value: not_active
                color: danger
                __UIBAKERY__SYSTEM_ID__: '16255749563400.24221659603719292'
            dataValue: '{{actions.dropdownValues.data}}'
            withData: true
          __UIBAKERY__RESPONSIVE__SHOW__CONDITION__CODE__:
            - xl
            - xs
          allowSelectAll:
            value: false
            dataValue: 'false'
            withData: false
          allowResetValue:
            value: false
            dataValue: 'false'
            withData: false
        index: 2
        actions: {}
        slots: []
      - id: '16208362762030.4920194651437575'
        definitionId: atomicCurrency
        parentSlotId: '16208362544700.44125583843162275'
        styles: {}
        properties:
          name: atomicCurrency
          prop: buyPrice
          primaryKey: false
          filter: true
          width: 90
          range:
            value: {}
            withData: false
            dataValue: '[0, 10]'
          __UIBAKERY__RESPONSIVE__SHOW__CONDITION__CODE__:
            - xl
            - xs
          filterVariation:
            value: range
            dataValue: range
            withData: false
        index: 7
        slots: []
      - id: '16208362762030.7128451435809413'
        definitionId: atomicText
        parentSlotId: '16208362544700.44125583843162275'
        styles: {}
        properties:
          name: atomicText2
          prop: productName
          __UIBAKERY__RESPONSIVE__SHOW__CONDITION__CODE__:
            - xl
            - xs
          length:
            value: {}
            withData: false
            dataValue: '[0, 10]'
          markdownSupport: true
          primaryKey: false
          filter: true
          width: '250'
          lines: '1'
        index: 1
        slots: []
